google_analytics:
highlighter:      pygments
markdown:         kramdown
title:            Robo Theme

links:
  - name: home
    url: /
  - name: posts
    url: /posts
  - name: about
    url: /#about
